In [1]:
import os

In [2]:
os.getcwd()

'd:\\ML Projects\\Credit_card_default_prediction_model\\notebook'

In [3]:
os.chdir("d:\\ML Projects\\Credit_card_default_prediction_model")

In [4]:
from default_prediction.config.configuration import Configuration

data_ingestion_log_completed


In [5]:
config= Configuration()

In [6]:
data_ingestion_config = config.get_data_ingestion_config()
data_validation_config = config.get_data_validation_config()
data_transformation_config = config.get_data_transformation_config()
model_trainer_config = config.get_model_trainer_config()

DataIngestionConfig(data_download_url='https://raw.githubusercontent.com/sumit9708/credit_card_dataset/main/cs-training.csv', csv_download_dir='d:\\ML Projects\\Credit_card_default_prediction_model\\default_prediction\\artifact\\data_ingestion\\2022-08-10-23-21-15\\csv_data', raw_data_dir='d:\\ML Projects\\Credit_card_default_prediction_model\\default_prediction\\artifact\\data_ingestion\\2022-08-10-23-21-15\\raw_data', schema_file_path='d:\\ML Projects\\Credit_card_default_prediction_model\\config\\schema.yaml', ingested_train_dir='d:\\ML Projects\\Credit_card_default_prediction_model\\default_prediction\\artifact\\data_ingestion\\2022-08-10-23-21-15\\ingested_data\\train', ingested_test_dir='d:\\ML Projects\\Credit_card_default_prediction_model\\default_prediction\\artifact\\data_ingestion\\2022-08-10-23-21-15\\ingested_data\\test')


In [7]:
from default_prediction.component.data_ingestion import DataIngestion

reached in data_ingestion inside component
log after data_ingestion


In [8]:
data_ingestion = DataIngestion(data_ingestion_config=data_ingestion_config)

In [9]:
data_ingestion_artifact = data_ingestion.initiate_data_ingestion()

In [10]:
from default_prediction.component.data_validation import DataValidation

In [11]:
data_validation = DataValidation(data_validation_config=data_validation_config,data_ingestion_artifact=data_ingestion_artifact)

In [12]:
data_validation_artifact = data_validation.initiate_data_validation()

In [13]:
from default_prediction.component.data_transformation import DataTransformation

In [14]:
data_transformation = DataTransformation(data_transformation_config=data_transformation_config,data_ingestion_artifact=data_ingestion_artifact,data_validation_artifact=data_validation_artifact)

In [15]:
data_transformation_artifact = data_transformation.initiate_data_transformation()

In [16]:
from default_prediction.component.model_training import ModelTrainer

In [17]:
model_training = ModelTrainer(model_trainer_config=model_trainer_config,data_transformation_artifact=data_transformation_artifact)

In [18]:
transformed_train_file_path = data_transformation_artifact.transformed_train_file_path

In [19]:
from default_prediction.constant import *
from default_prediction.util.util import *

In [20]:
train_array = load_numpy_array_data(file_path=transformed_train_file_path)

In [21]:
train_array

array([[-1.73203637, -0.02055845, -0.49255769, ..., -0.0573641 ,
         1.1435206 ,  1.        ],
       [-1.73200751, -0.01979326, -0.83132784, ..., -0.0573641 ,
         0.23832335,  0.        ],
       [-1.73197864, -0.02099085, -0.9668359 , ..., -0.0573641 ,
        -0.6668739 ,  0.        ],
       ...,
       [ 1.73197864, -0.02145691,  1.06578502, ..., -0.0573641 ,
        -0.6668739 ,  0.        ],
       [ 1.73200751, -0.02237894,  1.13353905, ..., -0.0573641 ,
        -0.6668739 ,  0.        ],
       [ 1.73203637, -0.02323384, -0.35704963, ..., -0.0573641 ,
         0.23832335,  0.        ]])

In [22]:
transformed_test_file_path = data_transformation_artifact.transformed_test_file_path
test_array = load_numpy_array_data(file_path=transformed_test_file_path)

In [23]:
test_array

array([[ 1.73206524, -0.02270537, -0.35704963, ..., -0.0573641 ,
         1.1435206 ,  0.        ],
       [ 1.73209411, -0.01996597,  0.18498262, ..., -0.0573641 ,
         1.1435206 ,  1.        ],
       [ 1.73212298, -0.02232679,  0.45599874, ...,  0.18624606,
         1.1435206 ,  0.        ],
       ...,
       [ 2.59800404, -0.02264174,  0.38824471, ..., -0.0573641 ,
        -0.6668739 ,  0.        ],
       [ 2.59803291, -0.02362732, -1.50886815, ..., -0.0573641 ,
        -0.6668739 ,  0.        ],
       [ 2.59806178, -0.02022134,  0.79476889, ..., -0.0573641 ,
        -0.6668739 ,  0.        ]])

In [24]:
x_train,y_train,x_test,y_test = train_array[:,:-1],train_array[:,-1],test_array[:,:-1],test_array[:,-1]

In [25]:
x_train

array([[-1.73203637, -0.02055845, -0.49255769, ...,  4.39433291,
        -0.0573641 ,  1.1435206 ],
       [-1.73200751, -0.01979326, -0.83132784, ..., -0.90014155,
        -0.0573641 ,  0.23832335],
       [-1.73197864, -0.02099085, -0.9668359 , ..., -0.90014155,
        -0.0573641 , -0.6668739 ],
       ...,
       [ 1.73197864, -0.02145691,  1.06578502, ..., -0.01772914,
        -0.0573641 , -0.6668739 ],
       [ 1.73200751, -0.02237894,  1.13353905, ..., -0.01772914,
        -0.0573641 , -0.6668739 ],
       [ 1.73203637, -0.02323384, -0.35704963, ..., -0.01772914,
        -0.0573641 ,  0.23832335]])

In [26]:
x_test

array([[ 1.73206524, -0.02270537, -0.35704963, ..., -0.01772914,
        -0.0573641 ,  1.1435206 ],
       [ 1.73209411, -0.01996597,  0.18498262, ..., -0.01772914,
        -0.0573641 ,  1.1435206 ],
       [ 1.73212298, -0.02232679,  0.45599874, ..., -0.01772914,
         0.18624606,  1.1435206 ],
       ...,
       [ 2.59800404, -0.02264174,  0.38824471, ..., -0.01772914,
        -0.0573641 , -0.6668739 ],
       [ 2.59803291, -0.02362732, -1.50886815, ..., -0.90014155,
        -0.0573641 , -0.6668739 ],
       [ 2.59806178, -0.02022134,  0.79476889, ...,  0.86468327,
        -0.0573641 , -0.6668739 ]])

In [27]:
y_train

array([1., 0., 0., ..., 0., 0., 0.])

In [28]:
y_test

array([0., 1., 0., ..., 0., 0., 0.])

In [29]:
model_config_file_path = model_trainer_config.model_config_file_path

In [30]:
model_config_file_path

'd:\\ML Projects\\Credit_card_default_prediction_model\\config\\model.yaml'

In [31]:
from default_prediction.entity.model_factory import ModelFactory

In [32]:
model_factory = ModelFactory(model_config_path=model_config_file_path)

In [33]:
base_accuracy = model_trainer_config.base_accuracy

In [34]:
base_accuracy

0.6

In [35]:
best_model = model_factory.get_best_model(X=x_train,y=y_train,base_accuracy=base_accuracy)

{'criterion': 'entropy', 'max_depth': 2}
{'cv': 5, 'verbose': 2, 'scoring': 'accuracy', 'penalty': ['l1', 'l2', 'elasticnet'], 'C': [1, 2, 5, 10, 15, 20, 30, 40, 50, 60]}
Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END .....................criterion=entropy, max_depth=2; total time=   0.2s
[CV] END .....................criterion=entropy, max_depth=2; total time=   0.1s
[CV] END .....................criterion=entropy, max_depth=2; total time=   0.1s
[CV] END .....................criterion=entropy, max_depth=2; total time=   0.1s
[CV] END .....................criterion=entropy, max_depth=2; total time=   0.0s
[CV] END ........................criterion=gini, max_depth=2; total time=   0.0s
[CV] END ........................criterion=gini, max_depth=2; total time=   0.0s
[CV] END ........................criterion=gini, max_depth=2; total time=   0.0s
[CV] END ........................criterion=gini, max_depth=2; total time=   0.0s
[CV] END ........................criteri

In [36]:
best_model

GridSearchedBestModel(model_serial_number='module_4', model=DecisionTreeClassifier(criterion='entropy', max_depth=2), best_model=DecisionTreeClassifier(max_depth=2), best_parameters={'criterion': 'gini', 'max_depth': 2}, best_score=0.9352750000000001)

In [37]:
from default_prediction.entity.model_factory import MetricInfoArtifactCategorical, ModelFactory,GridSearchedBestModel
from default_prediction.entity.model_factory import evaluate_classification_model
from typing import List

In [38]:
grid_searched_best_model_list:List[GridSearchedBestModel]=model_factory.grid_searched_best_model_list

In [39]:
grid_searched_best_model_list

[GridSearchedBestModel(model_serial_number='module_4', model=DecisionTreeClassifier(criterion='entropy', max_depth=2), best_model=DecisionTreeClassifier(max_depth=2), best_parameters={'criterion': 'gini', 'max_depth': 2}, best_score=0.9352750000000001)]

In [40]:
model_list = [model.best_model for model in grid_searched_best_model_list ]

In [41]:
model_list

[DecisionTreeClassifier(max_depth=2)]

In [42]:
from sklearn.metrics import precision_score,accuracy_score,recall_score,f1_score,confusion_matrix

In [43]:
def evaluate_classification_model(model_list: list, X_train:np.ndarray, y_train:np.ndarray, X_test:np.ndarray, y_test:np.ndarray, base_accuracy:float=0.6) -> MetricInfoArtifactCategorical:
    """
    Description:
    This function compare multiple regression model return best model
    Params:
    model_list: List of model
    X_train: Training dataset input feature
    y_train: Training dataset target feature
    X_test: Testing dataset input feature
    y_test: Testing dataset input feature
    return
    It retured a named tuple
    
    MetricInfoArtifactCategorical = namedtuple("MetricInfoArtifact",
                                ["model_name", "model_object", "train_confusion_matrix", "test_confusion_matrix", 
                                "train_accuracy",
                                 "test_accuracy", "model_accuracy","train_recall_score","test_recall_score",
                                 "train_precision_score","test_precision_score","train_f1_score",
                                 "test_f1_score","final_model_accuracy","index_number"])
    """
    try:
        
        #model_list = [model.best_model for model in model_list]
        index_number = 0
        metric_info_artifact = None
        for model in model_list:
            model_name = str(model)  #getting model name based on model object
            logging.info(f"{'>>'*30}Started evaluating model: [{type(model).__name__}] {'<<'*30}")
            
            #Getting prediction for training and testing dataset
            y_train_pred = model.predict(X_train)
            y_test_pred = model.predict(X_test)

            #Calculating accuracy using  Confusion matrix on training and testing dataset
            train_confusion_matrix = confusion_matrix(y_train, y_train_pred)
            test_confusion_matrix = confusion_matrix(y_test, y_test_pred)
            
            #Calculating accuracy score on training and testing dataset
            train_acc = accuracy_score(y_train, y_train_pred)
            test_acc = accuracy_score(y_test, y_test_pred)

            #Calculating recall_score on training and testing dataset
            train_recall_score = recall_score(y_train, y_train_pred)
            test_recall_score = recall_score(y_test, y_test_pred)

            #Calculating precision_score on training and testing dataset
            train_precision_score = precision_score(y_train, y_train_pred)
            test_precision_score = precision_score(y_test, y_test_pred)

            #Calculating f1_score on training and testing dataset
            train_f1_score = f1_score(y_train, y_train_pred)
            test_f1_score = f1_score(y_test, y_test_pred)

            # Calculating harmonic mean of train_accuracy and test_accuracy
            final_model_accuracy = (2 * (train_acc * test_acc)) / (train_acc + test_acc)
            diff_test_train_acc = abs(test_acc - train_acc)
            
            #logging all important metric
            logging.info(f"{'>>'*30} Score {'<<'*30}")
            logging.info(f"Train Score\t\t Test Score\t\t Average Score")
            logging.info(f"{train_acc}\t\t {test_acc}\t\t{final_model_accuracy}")

            logging.info(f"{'>>'*30} Loss {'<<'*30}")
            logging.info(f"Diff test train accuracy: [{diff_test_train_acc}].") 
            logging.info(f"Train confusion matrix: [{train_confusion_matrix}].")
            logging.info(f"Test confusion matrix: [{test_confusion_matrix}].")
            logging.info(f"train_recall_score: [{train_recall_score}].")
            logging.info(f"test_recall_score: [{test_recall_score}].")
            logging.info(f"train_precision_score: [{train_precision_score}].")
            logging.info(f"test_precision_score: [{test_precision_score}].")
            logging.info(f"train_f1_score: [{train_f1_score}].")
            logging.info(f"test_f1_score: [{test_f1_score}].")


            #if model accuracy is greater than base accuracy and train and test score is within certain thershold
            #we will accept that model as accepted model
            if final_model_accuracy >= base_accuracy and diff_test_train_acc < 0.05:
                base_accuracy = final_model_accuracy
                metric_info_artifact = MetricInfoArtifactCategorical(model_name=model_name,
                                                        model_object=model,
                                                        train_confusion_matrix=train_confusion_matrix,
                                                        test_confusion_matrix=test_confusion_matrix,
                                                        train_accuracy=train_acc,
                                                        test_accuracy=test_acc,
                                                        train_recall_score=train_recall_score,
                                                        test_recall_score=test_recall_score,
                                                        train_precision_score=train_precision_score,
                                                        test_precision_score=test_precision_score,
                                                        train_f1_score=train_f1_score,
                                                        test_f1_score=test_f1_score,
                                                        final_model_accuracy=final_model_accuracy,
                                                        index_number=index_number)

                logging.info(f"Acceptable model found {metric_info_artifact}. ")
            index_number += 1
        if metric_info_artifact is None:
            logging.info(f"No model found with higher accuracy than base accuracy")
        return metric_info_artifact
    except Exception as e:
        raise ExceptionHandler(e, sys) from e

In [44]:
for model in model_list:
    model_name = str(model)  #getting model name based on model object
    logging.info(f"{'>>'*30}Started evaluating model: [{type(model).__name__}] {'<<'*30}")

In [45]:
y_train_pred = model.predict(x_train)
y_test_pred = model.predict(x_test)

In [46]:
y_train_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [47]:
y_test_pred

array([0., 0., 0., ..., 0., 0., 0.])

In [48]:
train_confusion_matrix = confusion_matrix(y_train, y_train_pred)
test_confusion_matrix = confusion_matrix(y_test, y_test_pred)

In [49]:
train_confusion_matrix

array([[110882,   1136],
       [  6631,   1351]], dtype=int64)

In [50]:
test_confusion_matrix

array([[27704,   252],
       [ 1688,   356]], dtype=int64)

In [51]:
train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

In [52]:
train_acc

0.935275

In [53]:
test_acc

0.9353333333333333

In [54]:
train_acc = accuracy_score(y_train, y_train_pred)
test_acc = accuracy_score(y_test, y_test_pred)

In [55]:
train_acc

0.935275

In [56]:
test_acc

0.9353333333333333

In [57]:
train_recall_score = recall_score(y_train, y_train_pred)
test_recall_score = recall_score(y_test, y_test_pred)

In [58]:
train_recall_score

0.16925582560761715

In [59]:
test_recall_score

0.17416829745596868

In [60]:
train_precision_score = precision_score(y_train, y_train_pred)
test_precision_score = precision_score(y_test, y_test_pred)

In [61]:
train_precision_score

0.5432247687977483

In [62]:
test_precision_score

0.5855263157894737

In [63]:
train_f1_score = f1_score(y_train, y_train_pred)
test_f1_score = f1_score(y_test, y_test_pred)

In [64]:
test_f1_score

0.2684766214177979

In [65]:
model_accuracy = (2 * (train_acc * test_acc)) / (train_acc + test_acc)
diff_test_train_acc = abs(test_acc - train_acc)

In [66]:
model_accuracy

0.9353041657571289

In [67]:
diff_test_train_acc

5.833333333338242e-05

In [68]:
if model_accuracy >= base_accuracy and diff_test_train_acc < 0.05:
    base_accuracy = model_accuracy

In [69]:
base_accuracy

0.9353041657571289

In [70]:
index_number = 0
index_number += 1

In [71]:
metric_info_artifact = MetricInfoArtifactCategorical(model_name=model_name,
                                                        model_object=model,
                                                        train_confusion_matrix=train_confusion_matrix,
                                                        test_confusion_matrix=test_confusion_matrix,
                                                        train_accuracy=train_acc,
                                                        test_accuracy=test_acc,
                                                        train_recall_score=train_recall_score,
                                                        test_recall_score=test_recall_score,
                                                        train_precision_score=train_precision_score,
                                                        test_precision_score=test_precision_score,
                                                        train_f1_score=train_f1_score,
                                                        test_f1_score=test_f1_score,
                                                        final_model_accuracy=model_accuracy,
                                                        index_number=index_number)

In [72]:
metric_info:MetricInfoArtifactCategorical = evaluate_classification_model(model_list=model_list,X_train=x_train,y_train=y_train,X_test=x_test,y_test=y_test,base_accuracy=base_accuracy)

In [73]:
metric_info

MetricInfoArtifactCategorical(model_name='DecisionTreeClassifier(max_depth=2)', model_object=DecisionTreeClassifier(max_depth=2), train_confusion_matrix=array([[110882,   1136],
       [  6631,   1351]], dtype=int64), test_confusion_matrix=array([[27704,   252],
       [ 1688,   356]], dtype=int64), train_accuracy=0.935275, test_accuracy=0.9353333333333333, train_recall_score=0.16925582560761715, test_recall_score=0.17416829745596868, train_precision_score=0.5432247687977483, test_precision_score=0.5855263157894737, train_f1_score=0.2580953290667686, test_f1_score=0.2684766214177979, final_model_accuracy=0.9353041657571289, index_number=0)

In [74]:
preprocessing_obj=  load_object(file_path=data_transformation_artifact.preprocessed_object_file_path)

In [75]:
preprocessing_obj

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['CustomerID',
                                  'RevolvingUtilizationOfUnsecuredLines', 'age',
                                  'NumberOfTime30_to_59DaysPastDueNotWorse',
                                  'DebtRatio', 'MonthlyIncome',
                                  'NumberOfOpenCreditLinesAndLoans',
                                  'NumberOfTimes90DaysLate',
                                  'NumberRealEstateLoansOrLines',
                                  'NumberOfTime60_to_89DaysPastDueNotWorse',
                                  'NumberOfDependents'])])

In [76]:
model_object = metric_info.model_object

In [77]:
data_transformation_artifact

DataTransformationArtifact(is_transformed=True, message='Data transformation successfull.', transformed_train_file_path='d:\\ML Projects\\Credit_card_default_prediction_model\\default_prediction\\artifact\\data_transformation\\2022-08-10-23-21-15\\transformed_data\\train\\cs-training.npz', transformed_test_file_path='d:\\ML Projects\\Credit_card_default_prediction_model\\default_prediction\\artifact\\data_transformation\\2022-08-10-23-21-15\\transformed_data\\test\\cs-training.npz', preprocessed_object_file_path='d:\\ML Projects\\Credit_card_default_prediction_model\\default_prediction\\artifact\\data_transformation\\2022-08-10-23-21-15\\preprocessed\\preprocessed.pkl')